# Generated Config by Web Interface
minsupp=1.0
minconf=1.0
FindMutualExclusiveSets=true
FindConditionalMutualExclusiveSets=true
minzscore=-10.0
MaxSetSize=6
PvalueCutoff=0.0
sortByPathway=false
tumorsOfInterest=null
TimeLimit=0
DatasetName=example
FPGInputPathP1=/home/sukriye/Desktop/Projects/MEMNAR-WebServer/backend/mutation_data/example.txt
Rawinput=/home/sukriye/Desktop/Projects/MEMNAR-WebServer/backend/mutation_data/example.txt
PNARppItemsetsPath=itemsets.txt
PNARppRulesPath=rules.txt
MutualExclusiveSetsOutputPath=MutualExclusiveSets.txt
SecondTypeMutualExclusiveSetsOutputPath=MutualExclusiveSetsType2.txt
printItemsets=true
printRules=true
insertPathwaySimilaritiesToItemsets=true
insertPathwaySimilaritiesToRules=true
createHTMLoutput=true
ConditionalMutualExclusiveSetsHTMLOutputPath=ConditionalMutualExclusiveSets.html
MutualExclusiveSetsHTMLOutputPath=MutualExclusiveSets.html
mutMtxDataset=other
