# Generated Config by Web Interface
minsupp=1.0
minconf=0.3
FindMutualExclusiveSets=true
FindConditionalMutualExclusiveSets=true
minzscore=0.0
MaxSetSize=0
PvalueCutoff=0.0
sortByPathway=true
tumorsOfInterest=null
TimeLimit=0
DatasetName=mutation_data
FPGInputPathP1=mutation_data
Rawinput=mutation_data
PNARppItemsetsPath=itemsets.txt
PNARppRulesPath=rules.txt
MutualExclusiveSetsOutputPath=MutualExclusiveSets.txt
SecondTypeMutualExclusiveSetsOutputPath=MutualExclusiveSetsType2.txt
printItemsets=true
printRules=true
insertPathwaySimilaritiesToItemsets=true
insertPathwaySimilaritiesToRules=true
createHTMLoutput=true
ConditionalMutualExclusiveSetsHTMLOutputPath=ConditionalMutualExclusiveSets.html
MutualExclusiveSetsHTMLOutputPath=MutualExclusiveSets.html
mutMtxDataset=other
