# Generated Config by Web Interface
minsupp=0.0
minconf=0.0
FindMutualExclusiveSets=false
FindConditionalMutualExclusiveSets=false
minzscore=0.0
MaxSetSize=0
PvalueCutoff=0.0
sortByPathway=false
tumorsOfInterest=null
TimeLimit=0
DatasetName=mutation_data
FPGInputPathP1=mutation_data
Rawinput=mutation_data
PNARppItemsetsPath=itemsets.txt
PNARppRulesPath=rules.txt
MutualExclusiveSetsOutputPath=MutualExclusiveSets.txt
SecondTypeMutualExclusiveSetsOutputPath=MutualExclusiveSetsType2.txt
printItemsets=true
printRules=true
insertPathwaySimilaritiesToItemsets=true
insertPathwaySimilaritiesToRules=true
createHTMLoutput=true
ConditionalMutualExclusiveSetsHTMLOutputPath=ConditionalMutualExclusiveSets.html
MutualExclusiveSetsHTMLOutputPath=MutualExclusiveSets.html
mutMtxDataset=other
