# H2 Veritabanı Ayarları
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:MEMNAR-DB.db
spring.datasource.username=memnarweb
spring.datasource.password=memnarweb
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show_sql=true
spring.sql.init.mode=always

# JWT Ayarları
application.security.jwt.secret-key=CokGizliVeUzunBirAnahtarYazmalisinBurayaOrnekOlarak12345
application.security.jwt.expiration=86400000
