# H2 Veritabanı Ayarları
spring.datasource.url=jdbc:h2:mem:memnar_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console erişimi (Tarayıcıdan veritabanını görmek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Ayarları
application.security.jwt.secret-key=CokGizliVeUzunBirAnahtarYazmalisinBurayaOrnekOlarak12345
application.security.jwt.expiration=86400000
